export const refs = {
  categories: document.querySelector('.categories-list'),
  furnitureList: document.querySelector('.furniture-list'),
  loadMoreBtn: document.querySelector('.load-more'),
  loader: document.querySelector('.loader'),
  section: document.querySelector('[data-feedback-section]'),
  loader: document.querySelector('[data-feedback-loader]'),
  readyState: document.querySelector('[data-feedback-ready]'),
  list: document.querySelector('[data-feedback-list]'),
  prevBtn: document.querySelector('[data-feedback-prev]'),
  nextBtn: document.querySelector('[data-feedback-next]'),
  pagination: document.querySelector('[data-feedback-pagination]'),
  backdrop: document.querySelector('.backdrop'),
  modalCloseBtn: document.querySelector('.modal-close-btn'),
  modalContainer: document.querySelector('.product-modal'),
  orderBtn: document.querySelector('.order-btn'),
  productModal: document.querySelector('#product-backdrop'),
  orderModal: document.querySelector('#order-backdrop'),
};
